<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;

use \emdash\SpaceTraders\Utils\SpeakeasyMetadata;
class AcceptContractRequest
{
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=contractId')]
    public string $contractId;
    
	public function __construct()
	{
		$this->contractId = "";
	}
}
