<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class CreateShipWaypointScan201ApplicationJSONData
{
    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\Cooldown $cooldown
     */
	#[\JMS\Serializer\Annotation\SerializedName('cooldown')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Cooldown')]
    public \emdash\SpaceTraders\Models\Shared\Cooldown $cooldown;
    
    /**
     * $waypoints
     * 
     * @var array<\emdash\SpaceTraders\Models\Shared\ScannedWaypoint> $waypoints
     */
	#[\JMS\Serializer\Annotation\SerializedName('waypoints')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Shared\ScannedWaypoint>')]
    public array $waypoints;
    
	public function __construct()
	{
		$this->cooldown = new \emdash\SpaceTraders\Models\Shared\Cooldown();
		$this->waypoints = [];
	}
}
