<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class CreateChart201ApplicationJSONData
{
    /**
     * The chart of a system or waypoint, which makes the location visible to other agents.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\Chart $chart
     */
	#[\JMS\Serializer\Annotation\SerializedName('chart')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Chart')]
    public \emdash\SpaceTraders\Models\Shared\Chart $chart;
    
    /**
     * A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\Waypoint $waypoint
     */
	#[\JMS\Serializer\Annotation\SerializedName('waypoint')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Waypoint')]
    public \emdash\SpaceTraders\Models\Shared\Waypoint $waypoint;
    
	public function __construct()
	{
		$this->chart = new \emdash\SpaceTraders\Models\Shared\Chart();
		$this->waypoint = new \emdash\SpaceTraders\Models\Shared\Waypoint();
	}
}
