<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;

use \emdash\SpaceTraders\Utils\SpeakeasyMetadata;
class DeliverContractRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?DeliverContractRequestBody $requestBody = null;
    
    /**
     * The ID of the contract
     * 
     * @var string $contractId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=contractId')]
    public string $contractId;
    
	public function __construct()
	{
		$this->requestBody = null;
		$this->contractId = "";
	}
}
