<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class DeliverContractRequestBody
{
	#[\JMS\Serializer\Annotation\SerializedName('shipSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $shipSymbol;
    
	#[\JMS\Serializer\Annotation\SerializedName('tradeSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $tradeSymbol;
    
	#[\JMS\Serializer\Annotation\SerializedName('units')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $units;
    
	public function __construct()
	{
		$this->shipSymbol = "";
		$this->tradeSymbol = "";
		$this->units = 0;
	}
}
