<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class DockShipDockShip200ResponseData
{
    /**
     * The navigation information of the ship.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipNav $nav
     */
	#[\JMS\Serializer\Annotation\SerializedName('nav')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipNav')]
    public \emdash\SpaceTraders\Models\Shared\ShipNav $nav;
    
	public function __construct()
	{
		$this->nav = new \emdash\SpaceTraders\Models\Shared\ShipNav();
	}
}
