<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


/**
 * DockShipDockShip200Response - The ship has successfully docked at it's current location.
 * 
 * @package emdash\SpaceTraders\Models\Operations
 * @access public
 */
class DockShipDockShip200Response
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Operations\DockShipDockShip200ResponseData')]
    public DockShipDockShip200ResponseData $data;
    
	public function __construct()
	{
		$this->data = new \emdash\SpaceTraders\Models\Operations\DockShipDockShip200ResponseData();
	}
}
