<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class ExtractResourcesResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Created
     * 
     * @var ?\emdash\SpaceTraders\Models\Operations\ExtractResources201ApplicationJSON $extractResources201ApplicationJSONObject
     */
	
    public ?ExtractResources201ApplicationJSON $extractResources201ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->extractResources201ApplicationJSONObject = null;
	}
}
