<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class ExtractResourcesRequestBody
{
    /**
     * A resource survey of a waypoint, detailing a specific extraction location and the types of resources that can be found there.
     * 
     * @var ?\emdash\SpaceTraders\Models\Shared\Survey $survey
     */
	#[\JMS\Serializer\Annotation\SerializedName('survey')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Survey')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\emdash\SpaceTraders\Models\Shared\Survey $survey = null;
    
	public function __construct()
	{
		$this->survey = null;
	}
}
