<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class ExtractResources201ApplicationJSONData
{
	#[\JMS\Serializer\Annotation\SerializedName('cargo')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipCargo')]
    public \emdash\SpaceTraders\Models\Shared\ShipCargo $cargo;
    
    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\Cooldown $cooldown
     */
	#[\JMS\Serializer\Annotation\SerializedName('cooldown')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Cooldown')]
    public \emdash\SpaceTraders\Models\Shared\Cooldown $cooldown;
    
	#[\JMS\Serializer\Annotation\SerializedName('extraction')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Extraction')]
    public \emdash\SpaceTraders\Models\Shared\Extraction $extraction;
    
	public function __construct()
	{
		$this->cargo = new \emdash\SpaceTraders\Models\Shared\ShipCargo();
		$this->cooldown = new \emdash\SpaceTraders\Models\Shared\Cooldown();
		$this->extraction = new \emdash\SpaceTraders\Models\Shared\Extraction();
	}
}
