<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class FulfillContract200ApplicationJSONData
{
	#[\JMS\Serializer\Annotation\SerializedName('agent')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Agent')]
    public \emdash\SpaceTraders\Models\Shared\Agent $agent;
    
	#[\JMS\Serializer\Annotation\SerializedName('contract')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Contract')]
    public \emdash\SpaceTraders\Models\Shared\Contract $contract;
    
	public function __construct()
	{
		$this->agent = new \emdash\SpaceTraders\Models\Shared\Agent();
		$this->contract = new \emdash\SpaceTraders\Models\Shared\Contract();
	}
}
