<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class FulfillContractResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\emdash\SpaceTraders\Models\Operations\FulfillContract200ApplicationJSON $fulfillContract200ApplicationJSONObject
     */
	
    public ?FulfillContract200ApplicationJSON $fulfillContract200ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->fulfillContract200ApplicationJSONObject = null;
	}
}
