<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


/**
 * GetContract200ApplicationJSON - OK
 * 
 * @package emdash\SpaceTraders\Models\Operations
 * @access public
 */
class GetContract200ApplicationJSON
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Contract')]
    public \emdash\SpaceTraders\Models\Shared\Contract $data;
    
	public function __construct()
	{
		$this->data = new \emdash\SpaceTraders\Models\Shared\Contract();
	}
}
