<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;

use \emdash\SpaceTraders\Utils\SpeakeasyMetadata;
class GetFactionRequest
{
    /**
     * The faction symbol
     * 
     * @var string $factionSymbol
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=factionSymbol')]
    public string $factionSymbol;
    
	public function __construct()
	{
		$this->factionSymbol = "";
	}
}
