<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class GetStatus200ApplicationJSONLeaderboardsMostSubmittedCharts
{
	#[\JMS\Serializer\Annotation\SerializedName('agentSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $agentSymbol;
    
	#[\JMS\Serializer\Annotation\SerializedName('chartCount')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $chartCount;
    
	public function __construct()
	{
		$this->agentSymbol = "";
		$this->chartCount = 0;
	}
}
