<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


/**
 * GetSystems200ApplicationJSON - OK
 * 
 * @package emdash\SpaceTraders\Models\Operations
 * @access public
 */
class GetSystems200ApplicationJSON
{
    /**
     * $data
     * 
     * @var array<\emdash\SpaceTraders\Models\Shared\System> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Shared\System>')]
    public array $data;
    
	#[\JMS\Serializer\Annotation\SerializedName('meta')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Meta')]
    public \emdash\SpaceTraders\Models\Shared\Meta $meta;
    
	public function __construct()
	{
		$this->data = [];
		$this->meta = new \emdash\SpaceTraders\Models\Shared\Meta();
	}
}
