<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class GetShipNavResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * The current nav status of the ship.
     * 
     * @var ?\emdash\SpaceTraders\Models\Operations\GetShipNav200ApplicationJSON $getShipNav200ApplicationJSONObject
     */
	
    public ?GetShipNav200ApplicationJSON $getShipNav200ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getShipNav200ApplicationJSONObject = null;
	}
}
