<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


/**
 * GetStatus200ApplicationJSON - OK
 * 
 * @package emdash\SpaceTraders\Models\Operations
 * @access public
 */
class GetStatus200ApplicationJSON
{
    /**
     * $announcements
     * 
     * @var array<\emdash\SpaceTraders\Models\Operations\GetStatus200ApplicationJSONAnnouncements> $announcements
     */
	#[\JMS\Serializer\Annotation\SerializedName('announcements')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Operations\GetStatus200ApplicationJSONAnnouncements>')]
    public array $announcements;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $description;
    
	#[\JMS\Serializer\Annotation\SerializedName('leaderboards')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Operations\GetStatus200ApplicationJSONLeaderboards')]
    public GetStatus200ApplicationJSONLeaderboards $leaderboards;
    
    /**
     * $links
     * 
     * @var array<\emdash\SpaceTraders\Models\Operations\GetStatus200ApplicationJSONLinks> $links
     */
	#[\JMS\Serializer\Annotation\SerializedName('links')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Operations\GetStatus200ApplicationJSONLinks>')]
    public array $links;
    
    /**
     * The date and time when the game server was last reset.
     * 
     * @var string $resetDate
     */
	#[\JMS\Serializer\Annotation\SerializedName('resetDate')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $resetDate;
    
	#[\JMS\Serializer\Annotation\SerializedName('serverResets')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Operations\GetStatus200ApplicationJSONServerResets')]
    public GetStatus200ApplicationJSONServerResets $serverResets;
    
	#[\JMS\Serializer\Annotation\SerializedName('stats')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Operations\GetStatus200ApplicationJSONStats')]
    public GetStatus200ApplicationJSONStats $stats;
    
    /**
     * The current status of the game server.
     * 
     * @var string $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $status;
    
    /**
     * The current version of the API.
     * 
     * @var string $version
     */
	#[\JMS\Serializer\Annotation\SerializedName('version')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $version;
    
	public function __construct()
	{
		$this->announcements = [];
		$this->description = "";
		$this->leaderboards = new \emdash\SpaceTraders\Models\Operations\GetStatus200ApplicationJSONLeaderboards();
		$this->links = [];
		$this->resetDate = "";
		$this->serverResets = new \emdash\SpaceTraders\Models\Operations\GetStatus200ApplicationJSONServerResets();
		$this->stats = new \emdash\SpaceTraders\Models\Operations\GetStatus200ApplicationJSONStats();
		$this->status = "";
		$this->version = "";
	}
}
