<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class GetStatus200ApplicationJSONLeaderboards
{
    /**
     * $mostCredits
     * 
     * @var array<\emdash\SpaceTraders\Models\Operations\GetStatus200ApplicationJSONLeaderboardsMostCredits> $mostCredits
     */
	#[\JMS\Serializer\Annotation\SerializedName('mostCredits')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Operations\GetStatus200ApplicationJSONLeaderboardsMostCredits>')]
    public array $mostCredits;
    
    /**
     * $mostSubmittedCharts
     * 
     * @var array<\emdash\SpaceTraders\Models\Operations\GetStatus200ApplicationJSONLeaderboardsMostSubmittedCharts> $mostSubmittedCharts
     */
	#[\JMS\Serializer\Annotation\SerializedName('mostSubmittedCharts')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Operations\GetStatus200ApplicationJSONLeaderboardsMostSubmittedCharts>')]
    public array $mostSubmittedCharts;
    
	public function __construct()
	{
		$this->mostCredits = [];
		$this->mostSubmittedCharts = [];
	}
}
