<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class GetShipyardResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\emdash\SpaceTraders\Models\Operations\GetShipyard200ApplicationJSON $getShipyard200ApplicationJSONObject
     */
	
    public ?GetShipyard200ApplicationJSON $getShipyard200ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getShipyard200ApplicationJSONObject = null;
	}
}
