<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class GetStatus200ApplicationJSONStats
{
	#[\JMS\Serializer\Annotation\SerializedName('agents')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $agents;
    
	#[\JMS\Serializer\Annotation\SerializedName('ships')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $ships;
    
	#[\JMS\Serializer\Annotation\SerializedName('systems')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $systems;
    
	#[\JMS\Serializer\Annotation\SerializedName('waypoints')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $waypoints;
    
	public function __construct()
	{
		$this->agents = 0;
		$this->ships = 0;
		$this->systems = 0;
		$this->waypoints = 0;
	}
}
