<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class GetStatus200ApplicationJSONServerResets
{
    /**
     * How often we intend to reset the game server.
     * 
     * @var string $frequency
     */
	#[\JMS\Serializer\Annotation\SerializedName('frequency')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $frequency;
    
    /**
     * The date and time when the game server will reset.
     * 
     * @var string $next
     */
	#[\JMS\Serializer\Annotation\SerializedName('next')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $next;
    
	public function __construct()
	{
		$this->frequency = "";
		$this->next = "";
	}
}
