<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class GetStatus200ApplicationJSONLeaderboardsMostCredits
{
	#[\JMS\Serializer\Annotation\SerializedName('agentSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $agentSymbol;
    
	#[\JMS\Serializer\Annotation\SerializedName('credits')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $credits;
    
	public function __construct()
	{
		$this->agentSymbol = "";
		$this->credits = 0;
	}
}
