<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;

use \emdash\SpaceTraders\Utils\SpeakeasyMetadata;
class GetWaypointRequest
{
    /**
     * The system symbol
     * 
     * @var string $systemSymbol
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=systemSymbol')]
    public string $systemSymbol;
    
    /**
     * The waypoint symbol
     * 
     * @var string $waypointSymbol
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=waypointSymbol')]
    public string $waypointSymbol;
    
	public function __construct()
	{
		$this->systemSymbol = "";
		$this->waypointSymbol = "";
	}
}
