<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


/**
 * GetWaypoint200ApplicationJSON - OK
 * 
 * @package emdash\SpaceTraders\Models\Operations
 * @access public
 */
class GetWaypoint200ApplicationJSON
{
    /**
     * A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\Waypoint $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Waypoint')]
    public \emdash\SpaceTraders\Models\Shared\Waypoint $data;
    
	public function __construct()
	{
		$this->data = new \emdash\SpaceTraders\Models\Shared\Waypoint();
	}
}
