<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class Jettison200ApplicationJSONData
{
	#[\JMS\Serializer\Annotation\SerializedName('cargo')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipCargo')]
    public \emdash\SpaceTraders\Models\Shared\ShipCargo $cargo;
    
	public function __construct()
	{
		$this->cargo = new \emdash\SpaceTraders\Models\Shared\ShipCargo();
	}
}
