<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class JumpShip200ApplicationJSONData
{
    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\Cooldown $cooldown
     */
	#[\JMS\Serializer\Annotation\SerializedName('cooldown')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Cooldown')]
    public \emdash\SpaceTraders\Models\Shared\Cooldown $cooldown;
    
    /**
     * The navigation information of the ship.
     * 
     * @var ?\emdash\SpaceTraders\Models\Shared\ShipNav $nav
     */
	#[\JMS\Serializer\Annotation\SerializedName('nav')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipNav')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\emdash\SpaceTraders\Models\Shared\ShipNav $nav = null;
    
	public function __construct()
	{
		$this->cooldown = new \emdash\SpaceTraders\Models\Shared\Cooldown();
		$this->nav = null;
	}
}
