<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


/**
 * NavigateShip200ApplicationJSON - The successful transit information including the route details and changes to ship fuel, supplies, and crew wages paid. The route includes the expected time of arrival.
 * 
 * @package emdash\SpaceTraders\Models\Operations
 * @access public
 */
class NavigateShip200ApplicationJSON
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Operations\NavigateShip200ApplicationJSONData')]
    public NavigateShip200ApplicationJSONData $data;
    
	public function __construct()
	{
		$this->data = new \emdash\SpaceTraders\Models\Operations\NavigateShip200ApplicationJSONData();
	}
}
