<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class NegotiateContractResponse
{
	
    public string $contentType;
    
    /**
     * Created
     * 
     * @var ?\emdash\SpaceTraders\Models\Operations\NegotiateContractNegotiateContract200Response $negotiateContract200Response
     */
	
    public ?NegotiateContractNegotiateContract200Response $negotiateContract200Response = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->negotiateContract200Response = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
