<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


/**
 * NegotiateContractNegotiateContract200Response - Created
 * 
 * @package emdash\SpaceTraders\Models\Operations
 * @access public
 */
class NegotiateContractNegotiateContract200Response
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Operations\NegotiateContractNegotiateContract200ResponseData')]
    public NegotiateContractNegotiateContract200ResponseData $data;
    
	public function __construct()
	{
		$this->data = new \emdash\SpaceTraders\Models\Operations\NegotiateContractNegotiateContract200ResponseData();
	}
}
