<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


/**
 * OrbitShipOrbitShip200Response - The ship has successfully moved into orbit at it's current location.
 * 
 * @package emdash\SpaceTraders\Models\Operations
 * @access public
 */
class OrbitShipOrbitShip200Response
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Operations\OrbitShipOrbitShip200ResponseData')]
    public OrbitShipOrbitShip200ResponseData $data;
    
	public function __construct()
	{
		$this->data = new \emdash\SpaceTraders\Models\Operations\OrbitShipOrbitShip200ResponseData();
	}
}
