<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class PatchShipNavRequestBody
{
    /**
     * The ship's set speed when traveling between waypoints or systems.
     * 
     * @var ?\emdash\SpaceTraders\Models\Shared\ShipNavFlightMode $flightMode
     */
	#[\JMS\Serializer\Annotation\SerializedName('flightMode')]
    #[\JMS\Serializer\Annotation\Type('enum<emdash\SpaceTraders\Models\Shared\ShipNavFlightMode>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\emdash\SpaceTraders\Models\Shared\ShipNavFlightMode $flightMode = null;
    
	public function __construct()
	{
		$this->flightMode = null;
	}
}
