<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class PatchShipNavResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * The updated nav status of the ship.
     * 
     * @var ?\emdash\SpaceTraders\Models\Operations\PatchShipNav200ApplicationJSON $patchShipNav200ApplicationJSONObject
     */
	
    public ?PatchShipNav200ApplicationJSON $patchShipNav200ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->patchShipNav200ApplicationJSONObject = null;
	}
}
