<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


/**
 * PurchaseShip201ApplicationJSON - Created
 * 
 * @package emdash\SpaceTraders\Models\Operations
 * @access public
 */
class PurchaseShip201ApplicationJSON
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Operations\PurchaseShip201ApplicationJSONData')]
    public PurchaseShip201ApplicationJSONData $data;
    
	public function __construct()
	{
		$this->data = new \emdash\SpaceTraders\Models\Operations\PurchaseShip201ApplicationJSONData();
	}
}
