<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class PurchaseCargoResponse
{
	
    public string $contentType;
    
    /**
     * Created
     * 
     * @var ?\emdash\SpaceTraders\Models\Operations\PurchaseCargoPurchaseCargo201Response $purchaseCargo201Response
     */
	
    public ?PurchaseCargoPurchaseCargo201Response $purchaseCargo201Response = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->purchaseCargo201Response = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
