<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class PurchaseShip201ApplicationJSONData
{
	#[\JMS\Serializer\Annotation\SerializedName('agent')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Agent')]
    public \emdash\SpaceTraders\Models\Shared\Agent $agent;
    
    /**
     * A ship
     * 
     * @var \emdash\SpaceTraders\Models\Shared\Ship $ship
     */
	#[\JMS\Serializer\Annotation\SerializedName('ship')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Ship')]
    public \emdash\SpaceTraders\Models\Shared\Ship $ship;
    
	#[\JMS\Serializer\Annotation\SerializedName('transaction')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipyardTransaction')]
    public \emdash\SpaceTraders\Models\Shared\ShipyardTransaction $transaction;
    
	public function __construct()
	{
		$this->agent = new \emdash\SpaceTraders\Models\Shared\Agent();
		$this->ship = new \emdash\SpaceTraders\Models\Shared\Ship();
		$this->transaction = new \emdash\SpaceTraders\Models\Shared\ShipyardTransaction();
	}
}
