<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class RefuelShip200ApplicationJSONData
{
	#[\JMS\Serializer\Annotation\SerializedName('agent')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Agent')]
    public \emdash\SpaceTraders\Models\Shared\Agent $agent;
    
    /**
     * Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipFuel $fuel
     */
	#[\JMS\Serializer\Annotation\SerializedName('fuel')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipFuel')]
    public \emdash\SpaceTraders\Models\Shared\ShipFuel $fuel;
    
	#[\JMS\Serializer\Annotation\SerializedName('transaction')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\MarketTransaction')]
    public \emdash\SpaceTraders\Models\Shared\MarketTransaction $transaction;
    
	public function __construct()
	{
		$this->agent = new \emdash\SpaceTraders\Models\Shared\Agent();
		$this->fuel = new \emdash\SpaceTraders\Models\Shared\ShipFuel();
		$this->transaction = new \emdash\SpaceTraders\Models\Shared\MarketTransaction();
	}
}
