<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class RefuelShipResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\emdash\SpaceTraders\Models\Operations\RefuelShip200ApplicationJSON $refuelShip200ApplicationJSONObject
     */
	
    public ?RefuelShip200ApplicationJSON $refuelShip200ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->refuelShip200ApplicationJSONObject = null;
	}
}
