<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class Register201ApplicationJSONData
{
	#[\JMS\Serializer\Annotation\SerializedName('agent')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Agent')]
    public \emdash\SpaceTraders\Models\Shared\Agent $agent;
    
	#[\JMS\Serializer\Annotation\SerializedName('contract')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Contract')]
    public \emdash\SpaceTraders\Models\Shared\Contract $contract;
    
	#[\JMS\Serializer\Annotation\SerializedName('faction')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Faction')]
    public \emdash\SpaceTraders\Models\Shared\Faction $faction;
    
    /**
     * A ship
     * 
     * @var \emdash\SpaceTraders\Models\Shared\Ship $ship
     */
	#[\JMS\Serializer\Annotation\SerializedName('ship')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Ship')]
    public \emdash\SpaceTraders\Models\Shared\Ship $ship;
    
    /**
     * A Bearer token for accessing secured API endpoints.
     * 
     * @var string $token
     */
	#[\JMS\Serializer\Annotation\SerializedName('token')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $token;
    
	public function __construct()
	{
		$this->agent = new \emdash\SpaceTraders\Models\Shared\Agent();
		$this->contract = new \emdash\SpaceTraders\Models\Shared\Contract();
		$this->faction = new \emdash\SpaceTraders\Models\Shared\Faction();
		$this->ship = new \emdash\SpaceTraders\Models\Shared\Ship();
		$this->token = "";
	}
}
