<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class SellCargoResponse
{
	
    public string $contentType;
    
    /**
     * Created
     * 
     * @var ?\emdash\SpaceTraders\Models\Operations\SellCargoSellCargo201Response $sellCargo201Response
     */
	
    public ?SellCargoSellCargo201Response $sellCargo201Response = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->sellCargo201Response = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
