<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class SellCargoSellCargo201ResponseData
{
	#[\JMS\Serializer\Annotation\SerializedName('agent')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Agent')]
    public \emdash\SpaceTraders\Models\Shared\Agent $agent;
    
	#[\JMS\Serializer\Annotation\SerializedName('cargo')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipCargo')]
    public \emdash\SpaceTraders\Models\Shared\ShipCargo $cargo;
    
	#[\JMS\Serializer\Annotation\SerializedName('transaction')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\MarketTransaction')]
    public \emdash\SpaceTraders\Models\Shared\MarketTransaction $transaction;
    
	public function __construct()
	{
		$this->agent = new \emdash\SpaceTraders\Models\Shared\Agent();
		$this->cargo = new \emdash\SpaceTraders\Models\Shared\ShipCargo();
		$this->transaction = new \emdash\SpaceTraders\Models\Shared\MarketTransaction();
	}
}
