<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


/**
 * SellCargoSellCargo201Response - Created
 * 
 * @package emdash\SpaceTraders\Models\Operations
 * @access public
 */
class SellCargoSellCargo201Response
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Operations\SellCargoSellCargo201ResponseData')]
    public SellCargoSellCargo201ResponseData $data;
    
	public function __construct()
	{
		$this->data = new \emdash\SpaceTraders\Models\Operations\SellCargoSellCargo201ResponseData();
	}
}
