<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class ShipRefineShipRefine200ResponseDataProduced
{
	#[\JMS\Serializer\Annotation\SerializedName('tradeSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tradeSymbol = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('units')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $units = null;
    
	public function __construct()
	{
		$this->tradeSymbol = null;
		$this->units = null;
	}
}
