<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class ShipRefineResponse
{
	
    public string $contentType;
    
    /**
     * The ship has successfully started refining.
     * 
     * @var ?\emdash\SpaceTraders\Models\Operations\ShipRefineShipRefine200Response $shipRefine200Response
     */
	
    public ?ShipRefineShipRefine200Response $shipRefine200Response = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->shipRefine200Response = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
