<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class ShipRefineShipRefine200ResponseData
{
	#[\JMS\Serializer\Annotation\SerializedName('cargo')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipCargo')]
    public \emdash\SpaceTraders\Models\Shared\ShipCargo $cargo;
    
    /**
     * $consumed
     * 
     * @var array<\emdash\SpaceTraders\Models\Operations\ShipRefineShipRefine200ResponseDataConsumed> $consumed
     */
	#[\JMS\Serializer\Annotation\SerializedName('consumed')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Operations\ShipRefineShipRefine200ResponseDataConsumed>')]
    public array $consumed;
    
    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\Cooldown $cooldown
     */
	#[\JMS\Serializer\Annotation\SerializedName('cooldown')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\Cooldown')]
    public \emdash\SpaceTraders\Models\Shared\Cooldown $cooldown;
    
    /**
     * $produced
     * 
     * @var array<\emdash\SpaceTraders\Models\Operations\ShipRefineShipRefine200ResponseDataProduced> $produced
     */
	#[\JMS\Serializer\Annotation\SerializedName('produced')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Operations\ShipRefineShipRefine200ResponseDataProduced>')]
    public array $produced;
    
	public function __construct()
	{
		$this->cargo = new \emdash\SpaceTraders\Models\Shared\ShipCargo();
		$this->consumed = [];
		$this->cooldown = new \emdash\SpaceTraders\Models\Shared\Cooldown();
		$this->produced = [];
	}
}
