<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


/**
 * ShipRefineShipRefine200Response - The ship has successfully started refining.
 * 
 * @package emdash\SpaceTraders\Models\Operations
 * @access public
 */
class ShipRefineShipRefine200Response
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Operations\ShipRefineShipRefine200ResponseData')]
    public ShipRefineShipRefine200ResponseData $data;
    
	public function __construct()
	{
		$this->data = new \emdash\SpaceTraders\Models\Operations\ShipRefineShipRefine200ResponseData();
	}
}
