<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


enum ShipRefineRequestBodyProduce: string
{
    case Iron = 'IRON';
    case Copper = 'COPPER';
    case Silver = 'SILVER';
    case Gold = 'GOLD';
    case Aluminum = 'ALUMINUM';
    case Platinum = 'PLATINUM';
    case Uranite = 'URANITE';
    case Meritium = 'MERITIUM';
    case Fuel = 'FUEL';
}
