<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


enum ShipRefineRequestBodyProduce: string
{
    case IRON = 'IRON';
    case COPPER = 'COPPER';
    case SILVER = 'SILVER';
    case GOLD = 'GOLD';
    case ALUMINUM = 'ALUMINUM';
    case PLATINUM = 'PLATINUM';
    case URANITE = 'URANITE';
    case MERITIUM = 'MERITIUM';
    case FUEL = 'FUEL';
}
