<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class ShipRefineRequestBody
{
	#[\JMS\Serializer\Annotation\SerializedName('produce')]
    #[\JMS\Serializer\Annotation\Type('enum<emdash\SpaceTraders\Models\Operations\ShipRefineRequestBodyProduce>')]
    public ShipRefineRequestBodyProduce $produce;
    
	public function __construct()
	{
		$this->produce = \emdash\SpaceTraders\Models\Operations\ShipRefineRequestBodyProduce::IRON;
	}
}
