<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class WarpShipResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * The successful transit information including the route details and changes to ship fuel, supplies, and crew wages paid. The route includes the expected time of arrival.
     * 
     * @var ?\emdash\SpaceTraders\Models\Operations\WarpShip200ApplicationJSON $warpShip200ApplicationJSONObject
     */
	
    public ?WarpShip200ApplicationJSON $warpShip200ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->warpShip200ApplicationJSONObject = null;
	}
}
