<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Operations;


class WarpShipRequestBody
{
    /**
     * The target destination.
     * 
     * @var string $waypointSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('waypointSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $waypointSymbol;
    
	public function __construct()
	{
		$this->waypointSymbol = "";
	}
}
