<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/**
 * Chart - The chart of a system or waypoint, which makes the location visible to other agents.
 * 
 * @package emdash\SpaceTraders\Models\Shared
 * @access public
 */
class Chart
{
	#[\JMS\Serializer\Annotation\SerializedName('submittedBy')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $submittedBy = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('submittedOn')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $submittedOn = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('waypointSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $waypointSymbol = null;
    
	public function __construct()
	{
		$this->submittedBy = null;
		$this->submittedOn = null;
		$this->waypointSymbol = null;
	}
}
