<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/**
 * ContractDeliverGood - The details of a delivery contract. Includes the type of good, units needed, and the destination.
 * 
 * @package emdash\SpaceTraders\Models\Shared
 * @access public
 */
class ContractDeliverGood
{
    /**
     * The destination where goods need to be delivered.
     * 
     * @var string $destinationSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('destinationSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $destinationSymbol;
    
    /**
     * The symbol of the trade good to deliver.
     * 
     * @var string $tradeSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('tradeSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $tradeSymbol;
    
    /**
     * The number of units fulfilled on this contract.
     * 
     * @var int $unitsFulfilled
     */
	#[\JMS\Serializer\Annotation\SerializedName('unitsFulfilled')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $unitsFulfilled;
    
    /**
     * The number of units that need to be delivered on this contract.
     * 
     * @var int $unitsRequired
     */
	#[\JMS\Serializer\Annotation\SerializedName('unitsRequired')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $unitsRequired;
    
	public function __construct()
	{
		$this->destinationSymbol = "";
		$this->tradeSymbol = "";
		$this->unitsFulfilled = 0;
		$this->unitsRequired = 0;
	}
}
