<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


class ContractTerms
{
    /**
     * The deadline for the contract.
     * 
     * @var \DateTime $deadline
     */
	#[\JMS\Serializer\Annotation\SerializedName('deadline')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $deadline;
    
    /**
     * $deliver
     * 
     * @var ?array<\emdash\SpaceTraders\Models\Shared\ContractDeliverGood> $deliver
     */
	#[\JMS\Serializer\Annotation\SerializedName('deliver')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Shared\ContractDeliverGood>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $deliver = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('payment')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ContractPayment')]
    public ContractPayment $payment;
    
	public function __construct()
	{
		$this->deadline = new \DateTime();
		$this->deliver = null;
		$this->payment = new \emdash\SpaceTraders\Models\Shared\ContractPayment();
	}
}
