<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


class Contract
{
    /**
     * Whether the contract has been accepted by the agent
     * 
     * @var bool $accepted
     */
	#[\JMS\Serializer\Annotation\SerializedName('accepted')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $accepted;
    
    /**
     * The time at which the contract is no longer available to be accepted
     * 
     * @var ?\DateTime $deadlineToAccept
     */
	#[\JMS\Serializer\Annotation\SerializedName('deadlineToAccept')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $deadlineToAccept = null;
    
    /**
     * Deprecated in favor of deadlineToAccept
     * 
     * @var \DateTime $expiration
     */
	#[\JMS\Serializer\Annotation\SerializedName('expiration')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $expiration;
    
    /**
     * The symbol of the faction that this contract is for.
     * 
     * @var string $factionSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('factionSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $factionSymbol;
    
    /**
     * Whether the contract has been fulfilled
     * 
     * @var bool $fulfilled
     */
	#[\JMS\Serializer\Annotation\SerializedName('fulfilled')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $fulfilled;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('terms')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ContractTerms')]
    public ContractTerms $terms;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<emdash\SpaceTraders\Models\Shared\ContractType>')]
    public ContractType $type;
    
	public function __construct()
	{
		$this->accepted = false;
		$this->deadlineToAccept = null;
		$this->expiration = new \DateTime();
		$this->factionSymbol = "";
		$this->fulfilled = false;
		$this->id = "";
		$this->terms = new \emdash\SpaceTraders\Models\Shared\ContractTerms();
		$this->type = \emdash\SpaceTraders\Models\Shared\ContractType::PROCUREMENT;
	}
}
