<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


enum ContractType: string
{
    case PROCUREMENT = 'PROCUREMENT';
    case TRANSPORT = 'TRANSPORT';
    case SHUTTLE = 'SHUTTLE';
}
