<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


enum ContractType: string
{
    case Procurement = 'PROCUREMENT';
    case Transport = 'TRANSPORT';
    case Shuttle = 'SHUTTLE';
}
