<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/**
 * Cooldown - A cooldown is a period of time in which a ship cannot perform certain actions.
 * 
 * @package emdash\SpaceTraders\Models\Shared
 * @access public
 */
class Cooldown
{
    /**
     * The date and time when the cooldown expires in ISO 8601 format
     * 
     * @var ?\DateTime $expiration
     */
	#[\JMS\Serializer\Annotation\SerializedName('expiration')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $expiration = null;
    
    /**
     * The remaining duration of the cooldown in seconds
     * 
     * @var int $remainingSeconds
     */
	#[\JMS\Serializer\Annotation\SerializedName('remainingSeconds')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $remainingSeconds;
    
    /**
     * The symbol of the ship that is on cooldown
     * 
     * @var string $shipSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('shipSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $shipSymbol;
    
    /**
     * The total duration of the cooldown in seconds
     * 
     * @var int $totalSeconds
     */
	#[\JMS\Serializer\Annotation\SerializedName('totalSeconds')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalSeconds;
    
	public function __construct()
	{
		$this->expiration = null;
		$this->remainingSeconds = 0;
		$this->shipSymbol = "";
		$this->totalSeconds = 0;
	}
}
