<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


class Extraction
{
	#[\JMS\Serializer\Annotation\SerializedName('shipSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $shipSymbol;
    
	#[\JMS\Serializer\Annotation\SerializedName('yield')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ExtractionYield')]
    public ExtractionYield $yield;
    
	public function __construct()
	{
		$this->shipSymbol = "";
		$this->yield = new \emdash\SpaceTraders\Models\Shared\ExtractionYield();
	}
}
