<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/** The unique identifier of the trait. */
enum FactionTraitSymbol: string
{
    case BUREAUCRATIC = 'BUREAUCRATIC';
    case SECRETIVE = 'SECRETIVE';
    case CAPITALISTIC = 'CAPITALISTIC';
    case INDUSTRIOUS = 'INDUSTRIOUS';
    case PEACEFUL = 'PEACEFUL';
    case DISTRUSTFUL = 'DISTRUSTFUL';
    case WELCOMING = 'WELCOMING';
    case SMUGGLERS = 'SMUGGLERS';
    case SCAVENGERS = 'SCAVENGERS';
    case REBELLIOUS = 'REBELLIOUS';
    case EXILES = 'EXILES';
    case PIRATES = 'PIRATES';
    case RAIDERS = 'RAIDERS';
    case CLAN = 'CLAN';
    case GUILD = 'GUILD';
    case DOMINION = 'DOMINION';
    case FRINGE = 'FRINGE';
    case FORSAKEN = 'FORSAKEN';
    case ISOLATED = 'ISOLATED';
    case LOCALIZED = 'LOCALIZED';
    case ESTABLISHED = 'ESTABLISHED';
    case NOTABLE = 'NOTABLE';
    case DOMINANT = 'DOMINANT';
    case INESCAPABLE = 'INESCAPABLE';
    case INNOVATIVE = 'INNOVATIVE';
    case BOLD = 'BOLD';
    case VISIONARY = 'VISIONARY';
    case CURIOUS = 'CURIOUS';
    case DARING = 'DARING';
    case EXPLORATORY = 'EXPLORATORY';
    case RESOURCEFUL = 'RESOURCEFUL';
    case FLEXIBLE = 'FLEXIBLE';
    case COOPERATIVE = 'COOPERATIVE';
    case UNITED = 'UNITED';
    case STRATEGIC = 'STRATEGIC';
    case INTELLIGENT = 'INTELLIGENT';
    case RESEARCH_FOCUSED = 'RESEARCH_FOCUSED';
    case COLLABORATIVE = 'COLLABORATIVE';
    case PROGRESSIVE = 'PROGRESSIVE';
    case MILITARISTIC = 'MILITARISTIC';
    case TECHNOLOGICALLY_ADVANCED = 'TECHNOLOGICALLY_ADVANCED';
    case AGGRESSIVE = 'AGGRESSIVE';
    case IMPERIALISTIC = 'IMPERIALISTIC';
    case TREASURE_HUNTERS = 'TREASURE_HUNTERS';
    case DEXTEROUS = 'DEXTEROUS';
    case UNPREDICTABLE = 'UNPREDICTABLE';
    case BRUTAL = 'BRUTAL';
    case FLEETING = 'FLEETING';
    case ADAPTABLE = 'ADAPTABLE';
    case SELF_SUFFICIENT = 'SELF_SUFFICIENT';
    case DEFENSIVE = 'DEFENSIVE';
    case PROUD = 'PROUD';
    case DIVERSE = 'DIVERSE';
    case INDEPENDENT = 'INDEPENDENT';
    case SELF_INTERESTED = 'SELF_INTERESTED';
    case FRAGMENTED = 'FRAGMENTED';
    case COMMERCIAL = 'COMMERCIAL';
    case FREE_MARKETS = 'FREE_MARKETS';
    case ENTREPRENEURIAL = 'ENTREPRENEURIAL';
}
