<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/** The unique identifier of the trait. */
enum FactionTraitSymbol: string
{
    case Bureaucratic = 'BUREAUCRATIC';
    case Secretive = 'SECRETIVE';
    case Capitalistic = 'CAPITALISTIC';
    case Industrious = 'INDUSTRIOUS';
    case Peaceful = 'PEACEFUL';
    case Distrustful = 'DISTRUSTFUL';
    case Welcoming = 'WELCOMING';
    case Smugglers = 'SMUGGLERS';
    case Scavengers = 'SCAVENGERS';
    case Rebellious = 'REBELLIOUS';
    case Exiles = 'EXILES';
    case Pirates = 'PIRATES';
    case Raiders = 'RAIDERS';
    case Clan = 'CLAN';
    case Guild = 'GUILD';
    case Dominion = 'DOMINION';
    case Fringe = 'FRINGE';
    case Forsaken = 'FORSAKEN';
    case Isolated = 'ISOLATED';
    case Localized = 'LOCALIZED';
    case Established = 'ESTABLISHED';
    case Notable = 'NOTABLE';
    case Dominant = 'DOMINANT';
    case Inescapable = 'INESCAPABLE';
    case Innovative = 'INNOVATIVE';
    case Bold = 'BOLD';
    case Visionary = 'VISIONARY';
    case Curious = 'CURIOUS';
    case Daring = 'DARING';
    case Exploratory = 'EXPLORATORY';
    case Resourceful = 'RESOURCEFUL';
    case Flexible = 'FLEXIBLE';
    case Cooperative = 'COOPERATIVE';
    case United = 'UNITED';
    case Strategic = 'STRATEGIC';
    case Intelligent = 'INTELLIGENT';
    case ResearchFocused = 'RESEARCH_FOCUSED';
    case Collaborative = 'COLLABORATIVE';
    case Progressive = 'PROGRESSIVE';
    case Militaristic = 'MILITARISTIC';
    case TechnologicallyAdvanced = 'TECHNOLOGICALLY_ADVANCED';
    case Aggressive = 'AGGRESSIVE';
    case Imperialistic = 'IMPERIALISTIC';
    case TreasureHunters = 'TREASURE_HUNTERS';
    case Dexterous = 'DEXTEROUS';
    case Unpredictable = 'UNPREDICTABLE';
    case Brutal = 'BRUTAL';
    case Fleeting = 'FLEETING';
    case Adaptable = 'ADAPTABLE';
    case SelfSufficient = 'SELF_SUFFICIENT';
    case Defensive = 'DEFENSIVE';
    case Proud = 'PROUD';
    case Diverse = 'DIVERSE';
    case Independent = 'INDEPENDENT';
    case SelfInterested = 'SELF_INTERESTED';
    case Fragmented = 'FRAGMENTED';
    case Commercial = 'COMMERCIAL';
    case FreeMarkets = 'FREE_MARKETS';
    case Entrepreneurial = 'ENTREPRENEURIAL';
}
