<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


class JumpGate
{
    /**
     * The systems within range of the gate that have a corresponding gate.
     * 
     * @var array<\emdash\SpaceTraders\Models\Shared\ConnectedSystem> $connectedSystems
     */
	#[\JMS\Serializer\Annotation\SerializedName('connectedSystems')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Shared\ConnectedSystem>')]
    public array $connectedSystems;
    
    /**
     * The symbol of the faction that owns the gate.
     * 
     * @var ?string $factionSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('factionSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $factionSymbol = null;
    
    /**
     * The maximum jump range of the gate.
     * 
     * @var float $jumpRange
     */
	#[\JMS\Serializer\Annotation\SerializedName('jumpRange')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $jumpRange;
    
	public function __construct()
	{
		$this->connectedSystems = [];
		$this->factionSymbol = null;
		$this->jumpRange = 0;
	}
}
