<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


class MarketTradeGood
{
    /**
     * The price at which this good can be purchased from the market.
     * 
     * @var int $purchasePrice
     */
	#[\JMS\Serializer\Annotation\SerializedName('purchasePrice')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $purchasePrice;
    
    /**
     * The price at which this good can be sold to the market.
     * 
     * @var int $sellPrice
     */
	#[\JMS\Serializer\Annotation\SerializedName('sellPrice')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $sellPrice;
    
    /**
     * A rough estimate of the total supply of this good in the marketplace.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\MarketTradeGoodSupply $supply
     */
	#[\JMS\Serializer\Annotation\SerializedName('supply')]
    #[\JMS\Serializer\Annotation\Type('enum<emdash\SpaceTraders\Models\Shared\MarketTradeGoodSupply>')]
    public MarketTradeGoodSupply $supply;
    
    /**
     * The symbol of the trade good.
     * 
     * @var string $symbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('symbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $symbol;
    
    /**
     * The typical volume flowing through the market for this type of good. The larger the trade volume, the more stable prices will be.
     * 
     * @var int $tradeVolume
     */
	#[\JMS\Serializer\Annotation\SerializedName('tradeVolume')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $tradeVolume;
    
	public function __construct()
	{
		$this->purchasePrice = 0;
		$this->sellPrice = 0;
		$this->supply = \emdash\SpaceTraders\Models\Shared\MarketTradeGoodSupply::Scarce;
		$this->symbol = "";
		$this->tradeVolume = 0;
	}
}
