<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


class MarketTransaction
{
    /**
     * The price per unit of the transaction.
     * 
     * @var int $pricePerUnit
     */
	#[\JMS\Serializer\Annotation\SerializedName('pricePerUnit')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $pricePerUnit;
    
    /**
     * The symbol of the ship that made the transaction.
     * 
     * @var string $shipSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('shipSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $shipSymbol;
    
    /**
     * The timestamp of the transaction.
     * 
     * @var \DateTime $timestamp
     */
	#[\JMS\Serializer\Annotation\SerializedName('timestamp')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $timestamp;
    
    /**
     * The total price of the transaction.
     * 
     * @var int $totalPrice
     */
	#[\JMS\Serializer\Annotation\SerializedName('totalPrice')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalPrice;
    
    /**
     * The symbol of the trade good.
     * 
     * @var string $tradeSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('tradeSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $tradeSymbol;
    
    /**
     * The type of transaction.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\MarketTransactionType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<emdash\SpaceTraders\Models\Shared\MarketTransactionType>')]
    public MarketTransactionType $type;
    
    /**
     * The number of units of the transaction.
     * 
     * @var int $units
     */
	#[\JMS\Serializer\Annotation\SerializedName('units')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $units;
    
    /**
     * The symbol of the waypoint where the transaction took place.
     * 
     * @var string $waypointSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('waypointSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $waypointSymbol;
    
	public function __construct()
	{
		$this->pricePerUnit = 0;
		$this->shipSymbol = "";
		$this->timestamp = new \DateTime();
		$this->totalPrice = 0;
		$this->tradeSymbol = "";
		$this->type = \emdash\SpaceTraders\Models\Shared\MarketTransactionType::Purchase;
		$this->units = 0;
		$this->waypointSymbol = "";
	}
}
