<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/** The type of transaction. */
enum MarketTransactionType: string
{
    case PURCHASE = 'PURCHASE';
    case SELL = 'SELL';
}
