<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


class ShipyardShip
{
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $description;
    
    /**
     * The engine determines how quickly a ship travels between waypoints.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipEngine $engine
     */
	#[\JMS\Serializer\Annotation\SerializedName('engine')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipEngine')]
    public ShipEngine $engine;
    
    /**
     * The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipFrame $frame
     */
	#[\JMS\Serializer\Annotation\SerializedName('frame')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipFrame')]
    public ShipFrame $frame;
    
    /**
     * $modules
     * 
     * @var array<\emdash\SpaceTraders\Models\Shared\ShipModule> $modules
     */
	#[\JMS\Serializer\Annotation\SerializedName('modules')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Shared\ShipModule>')]
    public array $modules;
    
    /**
     * $mounts
     * 
     * @var array<\emdash\SpaceTraders\Models\Shared\ShipMount> $mounts
     */
	#[\JMS\Serializer\Annotation\SerializedName('mounts')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Shared\ShipMount>')]
    public array $mounts;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('purchasePrice')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $purchasePrice;
    
    /**
     * The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipReactor $reactor
     */
	#[\JMS\Serializer\Annotation\SerializedName('reactor')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipReactor')]
    public ShipReactor $reactor;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<emdash\SpaceTraders\Models\Shared\ShipType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ShipType $type = null;
    
	public function __construct()
	{
		$this->description = "";
		$this->engine = new \emdash\SpaceTraders\Models\Shared\ShipEngine();
		$this->frame = new \emdash\SpaceTraders\Models\Shared\ShipFrame();
		$this->modules = [];
		$this->mounts = [];
		$this->name = "";
		$this->purchasePrice = 0;
		$this->reactor = new \emdash\SpaceTraders\Models\Shared\ShipReactor();
		$this->type = null;
	}
}
