<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/**
 * ShipRequirements - The requirements for installation on a ship
 * 
 * @package emdash\SpaceTraders\Models\Shared
 * @access public
 */
class ShipRequirements
{
    /**
     * The number of crew required for operation.
     * 
     * @var ?int $crew
     */
	#[\JMS\Serializer\Annotation\SerializedName('crew')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $crew = null;
    
    /**
     * The amount of power required from the reactor.
     * 
     * @var ?int $power
     */
	#[\JMS\Serializer\Annotation\SerializedName('power')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $power = null;
    
    /**
     * The number of module slots required for installation.
     * 
     * @var ?int $slots
     */
	#[\JMS\Serializer\Annotation\SerializedName('slots')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $slots = null;
    
	public function __construct()
	{
		$this->crew = null;
		$this->power = null;
		$this->slots = null;
	}
}
