<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


enum ShipEngineSymbol: string
{
    case ENGINE_IMPULSE_DRIVE_I = 'ENGINE_IMPULSE_DRIVE_I';
    case ENGINE_ION_DRIVE_I = 'ENGINE_ION_DRIVE_I';
    case ENGINE_ION_DRIVE_II = 'ENGINE_ION_DRIVE_II';
    case ENGINE_HYPER_DRIVE_I = 'ENGINE_HYPER_DRIVE_I';
}
