<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


enum ShipModuleSymbol: string
{
    case ModuleMineralProcessorI = 'MODULE_MINERAL_PROCESSOR_I';
    case ModuleCargoHoldI = 'MODULE_CARGO_HOLD_I';
    case ModuleCrewQuartersI = 'MODULE_CREW_QUARTERS_I';
    case ModuleEnvoyQuartersI = 'MODULE_ENVOY_QUARTERS_I';
    case ModulePassengerCabinI = 'MODULE_PASSENGER_CABIN_I';
    case ModuleMicroRefineryI = 'MODULE_MICRO_REFINERY_I';
    case ModuleOreRefineryI = 'MODULE_ORE_REFINERY_I';
    case ModuleFuelRefineryI = 'MODULE_FUEL_REFINERY_I';
    case ModuleScienceLabI = 'MODULE_SCIENCE_LAB_I';
    case ModuleJumpDriveI = 'MODULE_JUMP_DRIVE_I';
    case ModuleJumpDriveIi = 'MODULE_JUMP_DRIVE_II';
    case ModuleJumpDriveIii = 'MODULE_JUMP_DRIVE_III';
    case ModuleWarpDriveI = 'MODULE_WARP_DRIVE_I';
    case ModuleWarpDriveIi = 'MODULE_WARP_DRIVE_II';
    case ModuleWarpDriveIii = 'MODULE_WARP_DRIVE_III';
    case ModuleShieldGeneratorI = 'MODULE_SHIELD_GENERATOR_I';
    case ModuleShieldGeneratorIi = 'MODULE_SHIELD_GENERATOR_II';
}
