<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/** The rotation of crew shifts. A stricter shift improves the ship's performance. A more relaxed shift improves the crew's morale. */
enum ShipCrewRotation: string
{
    case STRICT = 'STRICT';
    case RELAXED = 'RELAXED';
}
