<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


enum ShipFrameSymbol: string
{
    case FrameProbe = 'FRAME_PROBE';
    case FrameDrone = 'FRAME_DRONE';
    case FrameInterceptor = 'FRAME_INTERCEPTOR';
    case FrameRacer = 'FRAME_RACER';
    case FrameFighter = 'FRAME_FIGHTER';
    case FrameFrigate = 'FRAME_FRIGATE';
    case FrameShuttle = 'FRAME_SHUTTLE';
    case FrameExplorer = 'FRAME_EXPLORER';
    case FrameMiner = 'FRAME_MINER';
    case FrameLightFreighter = 'FRAME_LIGHT_FREIGHTER';
    case FrameHeavyFreighter = 'FRAME_HEAVY_FREIGHTER';
    case FrameTransport = 'FRAME_TRANSPORT';
    case FrameDestroyer = 'FRAME_DESTROYER';
    case FrameCruiser = 'FRAME_CRUISER';
    case FrameCarrier = 'FRAME_CARRIER';
}
