<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/** The registered role of the ship */
enum ShipRole: string
{
    case FABRICATOR = 'FABRICATOR';
    case HARVESTER = 'HARVESTER';
    case HAULER = 'HAULER';
    case INTERCEPTOR = 'INTERCEPTOR';
    case EXCAVATOR = 'EXCAVATOR';
    case TRANSPORT = 'TRANSPORT';
    case REPAIR = 'REPAIR';
    case SURVEYOR = 'SURVEYOR';
    case COMMAND = 'COMMAND';
    case CARRIER = 'CARRIER';
    case PATROL = 'PATROL';
    case SATELLITE = 'SATELLITE';
    case EXPLORER = 'EXPLORER';
    case REFINERY = 'REFINERY';
}
