<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


class Shipyard
{
    /**
     * The list of ship types available for purchase at this shipyard.
     * 
     * @var array<\emdash\SpaceTraders\Models\Shared\ShipyardShipTypes> $shipTypes
     */
	#[\JMS\Serializer\Annotation\SerializedName('shipTypes')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Shared\ShipyardShipTypes>')]
    public array $shipTypes;
    
    /**
     * The ships that are currently available for purchase at the shipyard.
     * 
     * @var ?array<\emdash\SpaceTraders\Models\Shared\ShipyardShip> $ships
     */
	#[\JMS\Serializer\Annotation\SerializedName('ships')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Shared\ShipyardShip>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $ships = null;
    
    /**
     * The symbol of the shipyard. The symbol is the same as the waypoint where the shipyard is located.
     * 
     * @var string $symbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('symbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $symbol;
    
    /**
     * The list of recent transactions at this shipyard.
     * 
     * @var ?array<\emdash\SpaceTraders\Models\Shared\ShipyardTransaction> $transactions
     */
	#[\JMS\Serializer\Annotation\SerializedName('transactions')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Shared\ShipyardTransaction>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $transactions = null;
    
	public function __construct()
	{
		$this->shipTypes = [];
		$this->ships = null;
		$this->symbol = "";
		$this->transactions = null;
	}
}
