<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/**
 * ShipReactor - The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons.
 * 
 * @package emdash\SpaceTraders\Models\Shared
 * @access public
 */
class ShipReactor
{
    /**
     * Condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new.
     * 
     * @var ?int $condition
     */
	#[\JMS\Serializer\Annotation\SerializedName('condition')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $condition = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $description;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('powerOutput')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $powerOutput;
    
    /**
     * The requirements for installation on a ship
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipRequirements $requirements
     */
	#[\JMS\Serializer\Annotation\SerializedName('requirements')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipRequirements')]
    public ShipRequirements $requirements;
    
	#[\JMS\Serializer\Annotation\SerializedName('symbol')]
    #[\JMS\Serializer\Annotation\Type('enum<emdash\SpaceTraders\Models\Shared\ShipReactorSymbol>')]
    public ShipReactorSymbol $symbol;
    
	public function __construct()
	{
		$this->condition = null;
		$this->description = "";
		$this->name = "";
		$this->powerOutput = 0;
		$this->requirements = new \emdash\SpaceTraders\Models\Shared\ShipRequirements();
		$this->symbol = \emdash\SpaceTraders\Models\Shared\ShipReactorSymbol::REACTOR_SOLAR_I;
	}
}
