<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/**
 * ShipNav - The navigation information of the ship.
 * 
 * @package emdash\SpaceTraders\Models\Shared
 * @access public
 */
class ShipNav
{
    /**
     * The ship's set speed when traveling between waypoints or systems.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipNavFlightMode $flightMode
     */
	#[\JMS\Serializer\Annotation\SerializedName('flightMode')]
    #[\JMS\Serializer\Annotation\Type('enum<emdash\SpaceTraders\Models\Shared\ShipNavFlightMode>')]
    public ShipNavFlightMode $flightMode;
    
    /**
     * The routing information for the ship's most recent transit or current location.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipNavRoute $route
     */
	#[\JMS\Serializer\Annotation\SerializedName('route')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipNavRoute')]
    public ShipNavRoute $route;
    
    /**
     * The current status of the ship
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipNavStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<emdash\SpaceTraders\Models\Shared\ShipNavStatus>')]
    public ShipNavStatus $status;
    
    /**
     * The system symbol of the ship's current location.
     * 
     * @var string $systemSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('systemSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $systemSymbol;
    
    /**
     * The waypoint symbol of the ship's current location, or if the ship is in-transit, the waypoint symbol of the ship's destination.
     * 
     * @var string $waypointSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('waypointSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $waypointSymbol;
    
	public function __construct()
	{
		$this->flightMode = \emdash\SpaceTraders\Models\Shared\ShipNavFlightMode::DRIFT;
		$this->route = new \emdash\SpaceTraders\Models\Shared\ShipNavRoute();
		$this->status = \emdash\SpaceTraders\Models\Shared\ShipNavStatus::IN_TRANSIT;
		$this->systemSymbol = "";
		$this->waypointSymbol = "";
	}
}
