<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


enum ShipMountDeposits: string
{
    case QuartzSand = 'QUARTZ_SAND';
    case SiliconCrystals = 'SILICON_CRYSTALS';
    case PreciousStones = 'PRECIOUS_STONES';
    case IceWater = 'ICE_WATER';
    case AmmoniaIce = 'AMMONIA_ICE';
    case IronOre = 'IRON_ORE';
    case CopperOre = 'COPPER_ORE';
    case SilverOre = 'SILVER_ORE';
    case AluminumOre = 'ALUMINUM_ORE';
    case GoldOre = 'GOLD_ORE';
    case PlatinumOre = 'PLATINUM_ORE';
    case Diamonds = 'DIAMONDS';
    case UraniteOre = 'URANITE_ORE';
    case MeritiumOre = 'MERITIUM_ORE';
}
