<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/**
 * ShipCrew - The ship's crew service and maintain the ship's systems and equipment.
 * 
 * @package emdash\SpaceTraders\Models\Shared
 * @access public
 */
class ShipCrew
{
    /**
     * The maximum number of crew members the ship can support.
     * 
     * @var int $capacity
     */
	#[\JMS\Serializer\Annotation\SerializedName('capacity')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $capacity;
    
    /**
     * The current number of crew members on the ship.
     * 
     * @var int $current
     */
	#[\JMS\Serializer\Annotation\SerializedName('current')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $current;
    
    /**
     * A rough measure of the crew's morale. A higher morale means the crew is happier and more productive. A lower morale means the ship is more prone to accidents.
     * 
     * @var int $morale
     */
	#[\JMS\Serializer\Annotation\SerializedName('morale')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $morale;
    
    /**
     * The minimum number of crew members required to maintain the ship.
     * 
     * @var int $required
     */
	#[\JMS\Serializer\Annotation\SerializedName('required')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $required;
    
    /**
     * The rotation of crew shifts. A stricter shift improves the ship's performance. A more relaxed shift improves the crew's morale.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipCrewRotation $rotation
     */
	#[\JMS\Serializer\Annotation\SerializedName('rotation')]
    #[\JMS\Serializer\Annotation\Type('enum<emdash\SpaceTraders\Models\Shared\ShipCrewRotation>')]
    public ShipCrewRotation $rotation;
    
    /**
     * The amount of credits per crew member paid per hour. Wages are paid when a ship docks at a civilized waypoint.
     * 
     * @var int $wages
     */
	#[\JMS\Serializer\Annotation\SerializedName('wages')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $wages;
    
	public function __construct()
	{
		$this->capacity = 0;
		$this->current = 0;
		$this->morale = 0;
		$this->required = 0;
		$this->rotation = \emdash\SpaceTraders\Models\Shared\ShipCrewRotation::Strict;
		$this->wages = 0;
	}
}
