<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/**
 * ShipFrame - The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
 * 
 * @package emdash\SpaceTraders\Models\Shared
 * @access public
 */
class ShipFrame
{
    /**
     * Condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new.
     * 
     * @var ?int $condition
     */
	#[\JMS\Serializer\Annotation\SerializedName('condition')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $condition = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $description;
    
	#[\JMS\Serializer\Annotation\SerializedName('fuelCapacity')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $fuelCapacity;
    
	#[\JMS\Serializer\Annotation\SerializedName('moduleSlots')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $moduleSlots;
    
	#[\JMS\Serializer\Annotation\SerializedName('mountingPoints')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $mountingPoints;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The requirements for installation on a ship
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipRequirements $requirements
     */
	#[\JMS\Serializer\Annotation\SerializedName('requirements')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipRequirements')]
    public ShipRequirements $requirements;
    
	#[\JMS\Serializer\Annotation\SerializedName('symbol')]
    #[\JMS\Serializer\Annotation\Type('enum<emdash\SpaceTraders\Models\Shared\ShipFrameSymbol>')]
    public ShipFrameSymbol $symbol;
    
	public function __construct()
	{
		$this->condition = null;
		$this->description = "";
		$this->fuelCapacity = 0;
		$this->moduleSlots = 0;
		$this->mountingPoints = 0;
		$this->name = "";
		$this->requirements = new \emdash\SpaceTraders\Models\Shared\ShipRequirements();
		$this->symbol = \emdash\SpaceTraders\Models\Shared\ShipFrameSymbol::FRAME_PROBE;
	}
}
