<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


class ShipyardShipTypes
{
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<emdash\SpaceTraders\Models\Shared\ShipType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ShipType $type = null;
    
	public function __construct()
	{
		$this->type = null;
	}
}
