<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


enum ShipEngineSymbol: string
{
    case EngineImpulseDriveI = 'ENGINE_IMPULSE_DRIVE_I';
    case EngineIonDriveI = 'ENGINE_ION_DRIVE_I';
    case EngineIonDriveIi = 'ENGINE_ION_DRIVE_II';
    case EngineHyperDriveI = 'ENGINE_HYPER_DRIVE_I';
}
