<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


enum ShipReactorSymbol: string
{
    case ReactorSolarI = 'REACTOR_SOLAR_I';
    case ReactorFusionI = 'REACTOR_FUSION_I';
    case ReactorFissionI = 'REACTOR_FISSION_I';
    case ReactorChemicalI = 'REACTOR_CHEMICAL_I';
    case ReactorAntimatterI = 'REACTOR_ANTIMATTER_I';
}
