<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/** The ship's set speed when traveling between waypoints or systems. */
enum ShipNavFlightMode: string
{
    case DRIFT = 'DRIFT';
    case STEALTH = 'STEALTH';
    case CRUISE = 'CRUISE';
    case BURN = 'BURN';
}
