<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


enum ShipType: string
{
    case ShipProbe = 'SHIP_PROBE';
    case ShipMiningDrone = 'SHIP_MINING_DRONE';
    case ShipInterceptor = 'SHIP_INTERCEPTOR';
    case ShipLightHauler = 'SHIP_LIGHT_HAULER';
    case ShipCommandFrigate = 'SHIP_COMMAND_FRIGATE';
    case ShipExplorer = 'SHIP_EXPLORER';
    case ShipHeavyFreighter = 'SHIP_HEAVY_FREIGHTER';
    case ShipLightShuttle = 'SHIP_LIGHT_SHUTTLE';
    case ShipOreHound = 'SHIP_ORE_HOUND';
    case ShipRefiningFreighter = 'SHIP_REFINING_FREIGHTER';
}
