<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/**
 * ShipRegistration - The public registration information of the ship
 * 
 * @package emdash\SpaceTraders\Models\Shared
 * @access public
 */
class ShipRegistration
{
    /**
     * The symbol of the faction the ship is registered with
     * 
     * @var string $factionSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('factionSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $factionSymbol;
    
    /**
     * The agent's registered name of the ship
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The registered role of the ship
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipRole $role
     */
	#[\JMS\Serializer\Annotation\SerializedName('role')]
    #[\JMS\Serializer\Annotation\Type('enum<emdash\SpaceTraders\Models\Shared\ShipRole>')]
    public ShipRole $role;
    
	public function __construct()
	{
		$this->factionSymbol = "";
		$this->name = "";
		$this->role = \emdash\SpaceTraders\Models\Shared\ShipRole::FABRICATOR;
	}
}
