<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/** The registered role of the ship */
enum ShipRole: string
{
    case Fabricator = 'FABRICATOR';
    case Harvester = 'HARVESTER';
    case Hauler = 'HAULER';
    case Interceptor = 'INTERCEPTOR';
    case Excavator = 'EXCAVATOR';
    case Transport = 'TRANSPORT';
    case Repair = 'REPAIR';
    case Surveyor = 'SURVEYOR';
    case Command = 'COMMAND';
    case Carrier = 'CARRIER';
    case Patrol = 'PATROL';
    case Satellite = 'SATELLITE';
    case Explorer = 'EXPLORER';
    case Refinery = 'REFINERY';
}
