<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


enum ShipMountDeposits: string
{
    case QUARTZ_SAND = 'QUARTZ_SAND';
    case SILICON_CRYSTALS = 'SILICON_CRYSTALS';
    case PRECIOUS_STONES = 'PRECIOUS_STONES';
    case ICE_WATER = 'ICE_WATER';
    case AMMONIA_ICE = 'AMMONIA_ICE';
    case IRON_ORE = 'IRON_ORE';
    case COPPER_ORE = 'COPPER_ORE';
    case SILVER_ORE = 'SILVER_ORE';
    case ALUMINUM_ORE = 'ALUMINUM_ORE';
    case GOLD_ORE = 'GOLD_ORE';
    case PLATINUM_ORE = 'PLATINUM_ORE';
    case DIAMONDS = 'DIAMONDS';
    case URANITE_ORE = 'URANITE_ORE';
    case MERITIUM_ORE = 'MERITIUM_ORE';
}
