<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


class ShipCargo
{
    /**
     * The max number of items that can be stored in the cargo hold.
     * 
     * @var int $capacity
     */
	#[\JMS\Serializer\Annotation\SerializedName('capacity')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $capacity;
    
    /**
     * The items currently in the cargo hold.
     * 
     * @var array<\emdash\SpaceTraders\Models\Shared\ShipCargoItem> $inventory
     */
	#[\JMS\Serializer\Annotation\SerializedName('inventory')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Shared\ShipCargoItem>')]
    public array $inventory;
    
    /**
     * The number of items currently stored in the cargo hold.
     * 
     * @var int $units
     */
	#[\JMS\Serializer\Annotation\SerializedName('units')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $units;
    
	public function __construct()
	{
		$this->capacity = 0;
		$this->inventory = [];
		$this->units = 0;
	}
}
