<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/**
 * Ship - A ship
 * 
 * @package emdash\SpaceTraders\Models\Shared
 * @access public
 */
class Ship
{
	#[\JMS\Serializer\Annotation\SerializedName('cargo')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipCargo')]
    public ShipCargo $cargo;
    
    /**
     * The ship's crew service and maintain the ship's systems and equipment.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipCrew $crew
     */
	#[\JMS\Serializer\Annotation\SerializedName('crew')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipCrew')]
    public ShipCrew $crew;
    
    /**
     * The engine determines how quickly a ship travels between waypoints.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipEngine $engine
     */
	#[\JMS\Serializer\Annotation\SerializedName('engine')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipEngine')]
    public ShipEngine $engine;
    
    /**
     * The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipFrame $frame
     */
	#[\JMS\Serializer\Annotation\SerializedName('frame')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipFrame')]
    public ShipFrame $frame;
    
    /**
     * Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipFuel $fuel
     */
	#[\JMS\Serializer\Annotation\SerializedName('fuel')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipFuel')]
    public ShipFuel $fuel;
    
    /**
     * $modules
     * 
     * @var array<\emdash\SpaceTraders\Models\Shared\ShipModule> $modules
     */
	#[\JMS\Serializer\Annotation\SerializedName('modules')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Shared\ShipModule>')]
    public array $modules;
    
    /**
     * $mounts
     * 
     * @var array<\emdash\SpaceTraders\Models\Shared\ShipMount> $mounts
     */
	#[\JMS\Serializer\Annotation\SerializedName('mounts')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Shared\ShipMount>')]
    public array $mounts;
    
    /**
     * The navigation information of the ship.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipNav $nav
     */
	#[\JMS\Serializer\Annotation\SerializedName('nav')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipNav')]
    public ShipNav $nav;
    
    /**
     * The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipReactor $reactor
     */
	#[\JMS\Serializer\Annotation\SerializedName('reactor')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipReactor')]
    public ShipReactor $reactor;
    
    /**
     * The public registration information of the ship
     * 
     * @var \emdash\SpaceTraders\Models\Shared\ShipRegistration $registration
     */
	#[\JMS\Serializer\Annotation\SerializedName('registration')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipRegistration')]
    public ShipRegistration $registration;
    
    /**
     * The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]_[HEX_ID]`
     * 
     * @var string $symbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('symbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $symbol;
    
	public function __construct()
	{
		$this->cargo = new \emdash\SpaceTraders\Models\Shared\ShipCargo();
		$this->crew = new \emdash\SpaceTraders\Models\Shared\ShipCrew();
		$this->engine = new \emdash\SpaceTraders\Models\Shared\ShipEngine();
		$this->frame = new \emdash\SpaceTraders\Models\Shared\ShipFrame();
		$this->fuel = new \emdash\SpaceTraders\Models\Shared\ShipFuel();
		$this->modules = [];
		$this->mounts = [];
		$this->nav = new \emdash\SpaceTraders\Models\Shared\ShipNav();
		$this->reactor = new \emdash\SpaceTraders\Models\Shared\ShipReactor();
		$this->registration = new \emdash\SpaceTraders\Models\Shared\ShipRegistration();
		$this->symbol = "";
	}
}
