<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/**
 * ShipFuel - Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
 * 
 * @package emdash\SpaceTraders\Models\Shared
 * @access public
 */
class ShipFuel
{
    /**
     * The maximum amount of fuel the ship's tanks can hold.
     * 
     * @var int $capacity
     */
	#[\JMS\Serializer\Annotation\SerializedName('capacity')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $capacity;
    
	#[\JMS\Serializer\Annotation\SerializedName('consumed')]
    #[\JMS\Serializer\Annotation\Type('emdash\SpaceTraders\Models\Shared\ShipFuelConsumed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ShipFuelConsumed $consumed = null;
    
    /**
     * The current amount of fuel in the ship's tanks.
     * 
     * @var int $current
     */
	#[\JMS\Serializer\Annotation\SerializedName('current')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $current;
    
	public function __construct()
	{
		$this->capacity = 0;
		$this->consumed = null;
		$this->current = 0;
	}
}
