<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


enum ShipMountSymbol: string
{
    case MountGasSiphonI = 'MOUNT_GAS_SIPHON_I';
    case MountGasSiphonIi = 'MOUNT_GAS_SIPHON_II';
    case MountGasSiphonIii = 'MOUNT_GAS_SIPHON_III';
    case MountSurveyorI = 'MOUNT_SURVEYOR_I';
    case MountSurveyorIi = 'MOUNT_SURVEYOR_II';
    case MountSurveyorIii = 'MOUNT_SURVEYOR_III';
    case MountSensorArrayI = 'MOUNT_SENSOR_ARRAY_I';
    case MountSensorArrayIi = 'MOUNT_SENSOR_ARRAY_II';
    case MountSensorArrayIii = 'MOUNT_SENSOR_ARRAY_III';
    case MountMiningLaserI = 'MOUNT_MINING_LASER_I';
    case MountMiningLaserIi = 'MOUNT_MINING_LASER_II';
    case MountMiningLaserIii = 'MOUNT_MINING_LASER_III';
    case MountLaserCannonI = 'MOUNT_LASER_CANNON_I';
    case MountMissileLauncherI = 'MOUNT_MISSILE_LAUNCHER_I';
    case MountTurretI = 'MOUNT_TURRET_I';
}
