<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/**
 * ShipCargoItem - The type of cargo item and the number of units.
 * 
 * @package emdash\SpaceTraders\Models\Shared
 * @access public
 */
class ShipCargoItem
{
    /**
     * The description of the cargo item type.
     * 
     * @var string $description
     */
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $description;
    
    /**
     * The name of the cargo item type.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The unique identifier of the cargo item type.
     * 
     * @var string $symbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('symbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $symbol;
    
    /**
     * The number of units of the cargo item.
     * 
     * @var int $units
     */
	#[\JMS\Serializer\Annotation\SerializedName('units')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $units;
    
	public function __construct()
	{
		$this->description = "";
		$this->name = "";
		$this->symbol = "";
		$this->units = 0;
	}
}
