<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


class ShipyardTransaction
{
    /**
     * The symbol of the agent that made the transaction.
     * 
     * @var string $agentSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('agentSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $agentSymbol;
    
    /**
     * The price of the transaction.
     * 
     * @var int $price
     */
	#[\JMS\Serializer\Annotation\SerializedName('price')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $price;
    
    /**
     * The symbol of the ship that was purchased.
     * 
     * @var string $shipSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('shipSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $shipSymbol;
    
    /**
     * The timestamp of the transaction.
     * 
     * @var \DateTime $timestamp
     */
	#[\JMS\Serializer\Annotation\SerializedName('timestamp')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $timestamp;
    
    /**
     * The symbol of the waypoint where the transaction took place.
     * 
     * @var string $waypointSymbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('waypointSymbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $waypointSymbol;
    
	public function __construct()
	{
		$this->agentSymbol = "";
		$this->price = 0;
		$this->shipSymbol = "";
		$this->timestamp = new \DateTime();
		$this->waypointSymbol = "";
	}
}
