<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/**
 * Survey - A resource survey of a waypoint, detailing a specific extraction location and the types of resources that can be found there.
 * 
 * @package emdash\SpaceTraders\Models\Shared
 * @access public
 */
class Survey
{
    /**
     * A list of deposits that can be found at this location.
     * 
     * @var array<\emdash\SpaceTraders\Models\Shared\SurveyDeposit> $deposits
     */
	#[\JMS\Serializer\Annotation\SerializedName('deposits')]
    #[\JMS\Serializer\Annotation\Type('array<emdash\SpaceTraders\Models\Shared\SurveyDeposit>')]
    public array $deposits;
    
    /**
     * The date and time when the survey expires. After this date and time, the survey will no longer be available for extraction.
     * 
     * @var \DateTime $expiration
     */
	#[\JMS\Serializer\Annotation\SerializedName('expiration')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $expiration;
    
    /**
     * A unique signature for the location of this survey. This signature is verified when attempting an extraction using this survey.
     * 
     * @var string $signature
     */
	#[\JMS\Serializer\Annotation\SerializedName('signature')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $signature;
    
    /**
     * The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.
     * 
     * @var \emdash\SpaceTraders\Models\Shared\SurveySize $size
     */
	#[\JMS\Serializer\Annotation\SerializedName('size')]
    #[\JMS\Serializer\Annotation\Type('enum<emdash\SpaceTraders\Models\Shared\SurveySize>')]
    public SurveySize $size;
    
    /**
     * The symbol of the waypoint that this survey is for.
     * 
     * @var string $symbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('symbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $symbol;
    
	public function __construct()
	{
		$this->deposits = [];
		$this->expiration = new \DateTime();
		$this->signature = "";
		$this->size = \emdash\SpaceTraders\Models\Shared\SurveySize::SMALL;
		$this->symbol = "";
	}
}
