<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/** The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted. */
enum SurveySize: string
{
    case SMALL = 'SMALL';
    case MODERATE = 'MODERATE';
    case LARGE = 'LARGE';
}
