<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/**
 * SurveyDeposit - A surveyed deposit of a mineral or resource available for extraction.
 * 
 * @package emdash\SpaceTraders\Models\Shared
 * @access public
 */
class SurveyDeposit
{
    /**
     * The symbol of the deposit.
     * 
     * @var string $symbol
     */
	#[\JMS\Serializer\Annotation\SerializedName('symbol')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $symbol;
    
	public function __construct()
	{
		$this->symbol = "";
	}
}
