<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


enum TradeSymbol: string
{
    case PreciousStones = 'PRECIOUS_STONES';
    case QuartzSand = 'QUARTZ_SAND';
    case SiliconCrystals = 'SILICON_CRYSTALS';
    case AmmoniaIce = 'AMMONIA_ICE';
    case LiquidHydrogen = 'LIQUID_HYDROGEN';
    case LiquidNitrogen = 'LIQUID_NITROGEN';
    case IceWater = 'ICE_WATER';
    case ExoticMatter = 'EXOTIC_MATTER';
    case AdvancedCircuitry = 'ADVANCED_CIRCUITRY';
    case GravitonEmitters = 'GRAVITON_EMITTERS';
    case Iron = 'IRON';
    case IronOre = 'IRON_ORE';
    case Copper = 'COPPER';
    case CopperOre = 'COPPER_ORE';
    case Aluminum = 'ALUMINUM';
    case AluminumOre = 'ALUMINUM_ORE';
    case Silver = 'SILVER';
    case SilverOre = 'SILVER_ORE';
    case Gold = 'GOLD';
    case GoldOre = 'GOLD_ORE';
    case Platinum = 'PLATINUM';
    case PlatinumOre = 'PLATINUM_ORE';
    case Diamonds = 'DIAMONDS';
    case Uranite = 'URANITE';
    case UraniteOre = 'URANITE_ORE';
    case Meritium = 'MERITIUM';
    case MeritiumOre = 'MERITIUM_ORE';
    case Hydrocarbon = 'HYDROCARBON';
    case Antimatter = 'ANTIMATTER';
    case Fertilizers = 'FERTILIZERS';
    case Fabrics = 'FABRICS';
    case Food = 'FOOD';
    case Jewelry = 'JEWELRY';
    case Machinery = 'MACHINERY';
    case Firearms = 'FIREARMS';
    case AssaultRifles = 'ASSAULT_RIFLES';
    case MilitaryEquipment = 'MILITARY_EQUIPMENT';
    case Explosives = 'EXPLOSIVES';
    case LabInstruments = 'LAB_INSTRUMENTS';
    case Ammunition = 'AMMUNITION';
    case Electronics = 'ELECTRONICS';
    case ShipPlating = 'SHIP_PLATING';
    case Equipment = 'EQUIPMENT';
    case Fuel = 'FUEL';
    case Medicine = 'MEDICINE';
    case Drugs = 'DRUGS';
    case Clothing = 'CLOTHING';
    case Microprocessors = 'MICROPROCESSORS';
    case Plastics = 'PLASTICS';
    case Polynucleotides = 'POLYNUCLEOTIDES';
    case Biocomposites = 'BIOCOMPOSITES';
    case Nanobots = 'NANOBOTS';
    case AiMainframes = 'AI_MAINFRAMES';
    case QuantumDrives = 'QUANTUM_DRIVES';
    case RoboticDrones = 'ROBOTIC_DRONES';
    case CyberImplants = 'CYBER_IMPLANTS';
    case GeneTherapeutics = 'GENE_THERAPEUTICS';
    case NeuralChips = 'NEURAL_CHIPS';
    case MoodRegulators = 'MOOD_REGULATORS';
    case ViralAgents = 'VIRAL_AGENTS';
    case MicroFusionGenerators = 'MICRO_FUSION_GENERATORS';
    case Supergrains = 'SUPERGRAINS';
    case LaserRifles = 'LASER_RIFLES';
    case Holographics = 'HOLOGRAPHICS';
    case ShipSalvage = 'SHIP_SALVAGE';
    case RelicTech = 'RELIC_TECH';
    case NovelLifeforms = 'NOVEL_LIFEFORMS';
    case BotanicalSpecimens = 'BOTANICAL_SPECIMENS';
    case CulturalArtifacts = 'CULTURAL_ARTIFACTS';
    case ReactorSolarI = 'REACTOR_SOLAR_I';
    case ReactorFusionI = 'REACTOR_FUSION_I';
    case ReactorFissionI = 'REACTOR_FISSION_I';
    case ReactorChemicalI = 'REACTOR_CHEMICAL_I';
    case ReactorAntimatterI = 'REACTOR_ANTIMATTER_I';
    case EngineImpulseDriveI = 'ENGINE_IMPULSE_DRIVE_I';
    case EngineIonDriveI = 'ENGINE_ION_DRIVE_I';
    case EngineIonDriveIi = 'ENGINE_ION_DRIVE_II';
    case EngineHyperDriveI = 'ENGINE_HYPER_DRIVE_I';
    case ModuleMineralProcessorI = 'MODULE_MINERAL_PROCESSOR_I';
    case ModuleCargoHoldI = 'MODULE_CARGO_HOLD_I';
    case ModuleCrewQuartersI = 'MODULE_CREW_QUARTERS_I';
    case ModuleEnvoyQuartersI = 'MODULE_ENVOY_QUARTERS_I';
    case ModulePassengerCabinI = 'MODULE_PASSENGER_CABIN_I';
    case ModuleMicroRefineryI = 'MODULE_MICRO_REFINERY_I';
    case ModuleOreRefineryI = 'MODULE_ORE_REFINERY_I';
    case ModuleFuelRefineryI = 'MODULE_FUEL_REFINERY_I';
    case ModuleScienceLabI = 'MODULE_SCIENCE_LAB_I';
    case ModuleJumpDriveI = 'MODULE_JUMP_DRIVE_I';
    case ModuleJumpDriveIi = 'MODULE_JUMP_DRIVE_II';
    case ModuleJumpDriveIii = 'MODULE_JUMP_DRIVE_III';
    case ModuleWarpDriveI = 'MODULE_WARP_DRIVE_I';
    case ModuleWarpDriveIi = 'MODULE_WARP_DRIVE_II';
    case ModuleWarpDriveIii = 'MODULE_WARP_DRIVE_III';
    case ModuleShieldGeneratorI = 'MODULE_SHIELD_GENERATOR_I';
    case ModuleShieldGeneratorIi = 'MODULE_SHIELD_GENERATOR_II';
    case MountGasSiphonI = 'MOUNT_GAS_SIPHON_I';
    case MountGasSiphonIi = 'MOUNT_GAS_SIPHON_II';
    case MountGasSiphonIii = 'MOUNT_GAS_SIPHON_III';
    case MountSurveyorI = 'MOUNT_SURVEYOR_I';
    case MountSurveyorIi = 'MOUNT_SURVEYOR_II';
    case MountSurveyorIii = 'MOUNT_SURVEYOR_III';
    case MountSensorArrayI = 'MOUNT_SENSOR_ARRAY_I';
    case MountSensorArrayIi = 'MOUNT_SENSOR_ARRAY_II';
    case MountSensorArrayIii = 'MOUNT_SENSOR_ARRAY_III';
    case MountMiningLaserI = 'MOUNT_MINING_LASER_I';
    case MountMiningLaserIi = 'MOUNT_MINING_LASER_II';
    case MountMiningLaserIii = 'MOUNT_MINING_LASER_III';
    case MountLaserCannonI = 'MOUNT_LASER_CANNON_I';
    case MountMissileLauncherI = 'MOUNT_MISSILE_LAUNCHER_I';
    case MountTurretI = 'MOUNT_TURRET_I';
}
