<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/** The type of waypoint. */
enum WaypointType: string
{
    case Planet = 'PLANET';
    case GasGiant = 'GAS_GIANT';
    case Moon = 'MOON';
    case OrbitalStation = 'ORBITAL_STATION';
    case JumpGate = 'JUMP_GATE';
    case AsteroidField = 'ASTEROID_FIELD';
    case Nebula = 'NEBULA';
    case DebrisField = 'DEBRIS_FIELD';
    case GravityWell = 'GRAVITY_WELL';
}
