<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders\Models\Shared;


/** The unique identifier of the trait. */
enum WaypointTraitSymbol: string
{
    case Uncharted = 'UNCHARTED';
    case Marketplace = 'MARKETPLACE';
    case Shipyard = 'SHIPYARD';
    case Outpost = 'OUTPOST';
    case ScatteredSettlements = 'SCATTERED_SETTLEMENTS';
    case SprawlingCities = 'SPRAWLING_CITIES';
    case MegaStructures = 'MEGA_STRUCTURES';
    case Overcrowded = 'OVERCROWDED';
    case HighTech = 'HIGH_TECH';
    case Corrupt = 'CORRUPT';
    case Bureaucratic = 'BUREAUCRATIC';
    case TradingHub = 'TRADING_HUB';
    case Industrial = 'INDUSTRIAL';
    case BlackMarket = 'BLACK_MARKET';
    case ResearchFacility = 'RESEARCH_FACILITY';
    case MilitaryBase = 'MILITARY_BASE';
    case SurveillanceOutpost = 'SURVEILLANCE_OUTPOST';
    case ExplorationOutpost = 'EXPLORATION_OUTPOST';
    case MineralDeposits = 'MINERAL_DEPOSITS';
    case CommonMetalDeposits = 'COMMON_METAL_DEPOSITS';
    case PreciousMetalDeposits = 'PRECIOUS_METAL_DEPOSITS';
    case RareMetalDeposits = 'RARE_METAL_DEPOSITS';
    case MethanePools = 'METHANE_POOLS';
    case IceCrystals = 'ICE_CRYSTALS';
    case ExplosiveGases = 'EXPLOSIVE_GASES';
    case StrongMagnetosphere = 'STRONG_MAGNETOSPHERE';
    case VibrantAuroras = 'VIBRANT_AURORAS';
    case SaltFlats = 'SALT_FLATS';
    case Canyons = 'CANYONS';
    case PerpetualDaylight = 'PERPETUAL_DAYLIGHT';
    case PerpetualOvercast = 'PERPETUAL_OVERCAST';
    case DrySeabeds = 'DRY_SEABEDS';
    case MagmaSeas = 'MAGMA_SEAS';
    case Supervolcanoes = 'SUPERVOLCANOES';
    case AshClouds = 'ASH_CLOUDS';
    case VastRuins = 'VAST_RUINS';
    case MutatedFlora = 'MUTATED_FLORA';
    case Terraformed = 'TERRAFORMED';
    case ExtremeTemperatures = 'EXTREME_TEMPERATURES';
    case ExtremePressure = 'EXTREME_PRESSURE';
    case DiverseLife = 'DIVERSE_LIFE';
    case ScarceLife = 'SCARCE_LIFE';
    case Fossils = 'FOSSILS';
    case WeakGravity = 'WEAK_GRAVITY';
    case StrongGravity = 'STRONG_GRAVITY';
    case CrushingGravity = 'CRUSHING_GRAVITY';
    case ToxicAtmosphere = 'TOXIC_ATMOSPHERE';
    case CorrosiveAtmosphere = 'CORROSIVE_ATMOSPHERE';
    case BreathableAtmosphere = 'BREATHABLE_ATMOSPHERE';
    case Jovian = 'JOVIAN';
    case Rocky = 'ROCKY';
    case Volcanic = 'VOLCANIC';
    case Frozen = 'FROZEN';
    case Swamp = 'SWAMP';
    case Barren = 'BARREN';
    case Temperate = 'TEMPERATE';
    case Jungle = 'JUNGLE';
    case Ocean = 'OCEAN';
    case Stripped = 'STRIPPED';
}
