<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace emdash\SpaceTraders;

/**
 * SpaceTradersBuilder is used to configure and build an instance of the SDK.
 * 
 * @package emdash\SpaceTraders
 */
class SpaceTradersBuilder
{
    private ?\GuzzleHttp\ClientInterface $client;
    private ?Models\Shared\Security $security;
    private string $serverUrl;
    /** @var array<string, string> */
    private ?array $params;

    public function __construct() {
        $this->client = null;
        $this->security = null;
        $this->serverUrl = '';
        $this->params = null;
    }

    /**
     * setClient allows setting a custom Guzzle client for the SDK to make requests with.
     *
     * @param \GuzzleHttp\ClientInterface $client
     * @return SpaceTradersBuilder
     */
    public function setClient(\GuzzleHttp\ClientInterface $client): SpaceTradersBuilder
    {
        $this->client = $client;
        return $this;
    }
    
    /**
     * setSecurity is used to configure the security required for the SDK.
     *
     * @param Models\Shared\Security $security
     * @return SpaceTradersBuilder
     */
    public function setSecurity(Models\Shared\Security $security): SpaceTradersBuilder
    {
        $this->security = $security;
        return $this;
    }
    
    /**
     * setServerUrl is used to configure the server URL for the SDK, and optionally template any parameters in the URL.
     *
     * @param string $serverUrl
     * @param array<string, string> $params
     * @return SpaceTradersBuilder
     */
    public function setServerUrl(string $serverUrl, ?array $params = null): SpaceTradersBuilder
    {
        $this->serverUrl = $serverUrl;
        if ($params !== null) {
            $this->params = $params;
        }
        return $this;
    }
    
    /**
     * build is used to build the SDK with any of the configured options.
     *
     * @return SpaceTraders
     */
    public function build(): SpaceTraders
    {
        return new SpaceTraders($this->client, $this->security, $this->serverUrl, $this->params);
    }
}